### ISSUE TITLE
R[write to console]: Error in gzfile(file, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by samirama** [LPioL/MultiVERSE#6]
I have a similar problem, could you please help me with this? I don't face this problem while I'm using Multiplex network, only appears with heterogeneous one:

[1] "Reading arguments..."
[1] "Input network with 3 Layers"
[1] "Input network with 3 Layers"
[1] "Input network with 1 Layers"
Generating bipartite matrix...
Expanding bipartite matrix to fit the multiplex network...
Computing adjacency matrix of the first input network...
Computing adjacency matrix of the second input network...
Computing inter-subnetworks transitions...
RWR done
R[write to console]: Error in gzfile(file, "rb") : cannot open the connection

R[write to console]: In addition:
R[write to console]: Warning message:

R[write to console]: In gzfile(file, "rb") :
R[write to console]:

R[write to console]:  cannot open compressed file './ResultsRWR/MatrixSimilarityMultiplexHettest_MH.rds', probable reason 'No such file or directory'

Traceback (most recent call last):
  File "MultiVERSE_MH.py", line 119, in <module>
    main()
  File "MultiVERSE_MH.py", line 85, in main
    r_DistancematrixPPI = r_readRDS('./ResultsRWR/MatrixSimilarityMultiplexHet'+graph_name +'.rds')
  File "/home/samira/miniconda3/envs/MP/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/home/samira/miniconda3/envs/MP/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/samira/miniconda3/envs/MP/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/samira/miniconda3/envs/MP/lib/python3.7/site-packages/rpy2/rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in gzfile(file, "rb") : cannot open the connection

**Comment by trevdog94** [comment]
I am also facing the same issue
